name:                dashboard
version:             0.1.0.0
github:              "githubuser/dashboard"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dashboard#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html == 0.9.1.1
- blaze-markup == 0.8.2.2
- happstack-server == 7.5.1.3
- heterocephalus  == 1.0.5.3
- wreq == 0.5.3.1
- lens == 4.17
- aeson == 1.4.2.0
- aeson-lens # == 0.5.0.0 # 1.0.2???
- text == 1.2.3.1
- http-client == 0.5.14
- bytestring == 0.10.8.2
- unordered-containers == 0.2.9.0
- vector == 0.12.0.2
library:
  source-dirs: src

executables:
  dashboard-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dashboard

tests:
  dashboard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dashboard

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - ScopedTypeVariables